#!/usr/bin/env python2
'''
tmuxssh

Usage:
  tmuxssh [--user=<user>] [--pem=<pem>] <hosts>
  tmuxssh --version
  tmuxssh -h | --help

'''

import os
import subprocess
import docopt


def main(hosts, user=None, pem=None):
    with TmuxSession('tmux-{}'.format(os.getpid())) as tmux:
        for host in hosts.split():
            tmux.split_window(list(compose_ssh_command(host, user, pem)))
            tmux.select_layout('tiled')
        tmux.kill_pane(0)
        tmux.select_layout('tiled')
        tmux.set_window_option('synchronize-panes', 'on')
        tmux.attach()


class TmuxSession(object):

    def __init__(self, session_name):
        self._session_name = session_name
        subprocess.call(['tmux', 'new-session', '-ds', self._session_name])

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.kill_session()

    def split_window(self, command):
        if isinstance(command, str):
            command = [command]
        subprocess.call(['tmux', 'split-window', '-v', '-t', self._session_name] + command)

    def select_layout(self, layout):
        subprocess.call(['tmux', 'select-layout', '-t', self._session_name, layout])

    def attach(self):
        subprocess.call(['tmux', 'attach', '-t', self._session_name])

    def set_window_option(self, option, value):
        subprocess.call(['tmux', 'set-window-option', '-t', self._session_name, option, value])

    def kill_pane(self, n):
        subprocess.call(['tmux', 'kill-pane', '-t', str(n)])

    def kill_session(self):
        subprocess.call(['tmux', 'kill-session', '-t', self._session_name])


def compose_ssh_command(host, user=None, pem=None):
    yield 'ssh'
    if pem:
        yield '-i'
        yield pem
    if user:
        yield '{}@{}'.format(user, host)
    else:
        yield host


if __name__ == '__main__':
    args = docopt.docopt(__doc__, version='0.0.1')
    main(args.get('<hosts>'), user=args.get('--user'), pem=args.get('--pem'))

